### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by LeGoffLoic** [cedricB/skinIO#1]
The export methods seem to work, but when I try to import I have the following error. (In all modes)
I'm using maya 2016

validation.py", line 311, in processInputSetting
maya.cmds.namespace(setNamespace=self.namespacePrefix)
RuntimeError: No namespace matches name: 'skinNamespace_weights'.

**Comment by cedricB** [comment]
Hi Loic, thanks for the report ,
is it the full error log?

are you saving mesh or other kind of shape?

2018-01-25 15:21 GMT-06:00 LeGoffLoic <notifications@github.com>:

**Comment by LeGoffLoic** [comment]
I gave it an other try this morning and it's now working ... I've tried so many times yesterday ...
This is not erroring but the ascii version doesn't reload the weights properly. when the binary works just fine.

How easy would it be to make it work for other kind of shapes like curves or nurbs ?

**Comment by cedricB** [comment]
Normaly , the work is already layout for this but i didn't put that much
time to do proper testing( was saving weight on particles, ffd as well on
other project).
let me check on my side.

2018-01-26 12:51 GMT-05:00 LeGoffLoic <notifications@github.com>:

**Comment by cedricB** [comment]
OK so i submit a fix for the namespace error and did test out successfully saving/importing weights on mesh/curve,nurbsSurface and lattice.

I used Alembic injection mode.
Let me know how it behave on your side
